version: '3.7'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    tty: true
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/var/www