<template>
    <NuxtLayout name="home">
      <div class="container min-h-screen px-4 py-12 mx-auto">
        <h1 class="mb-4 text-2xl font-bold">{{ categoryName }}</h1>
        <div class="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3">
          <ProductCard
            v-for="product in filteredProducts"
            :key="product.id"
            :product="product"
          />
        </div>
      </div>
    </NuxtLayout>
  </template>
  
  <script setup>
  import { ref, computed } from 'vue';
  import { useRoute } from 'vue-router';
  import ProductCard from '~/composables/reuseable/ProductCard/ProductCard.vue';
  
  const route = useRoute();
  const categoryId = ref(route.params.id); // Get category ID from route params
  
  const categories = ref([
    { id: 1, name: "Phones" },
    { id: 2, name: "Computers" },
    { id: 3, name: "SmartWatch" },
    { id: 4, name: "Camera" },
    { id: 5, name: "HeadPhones" },
    { id: 6, name: "Gaming" },
    { id: 7, name: "Microphone" },
    { id: 8, name: "Clothing" },
    { id: 9, name: "Electronics" },
    { id: 10, name: "Home Appliances" },
    { id: 11, name: "jewelery" },
  ]);
  
  const products = ref([
  {
    id: 1,
    name: "The north coat",
    image: "/images/pro-1.png",
    price: "$260",
    prevPrice: "$360",
    rating: 4,
    ratingCount: 65,
    discount: "-40%",
    brand: "Apple",
    color: "Red",
    vendor: "Vendor1",
    categories: ["Clothing"],
  },
  {
    id: 2,
    name: "Gucci duffle bag",
    image: "/images/bag.png",
    price: "$960",
    prevPrice: "$1160",
    rating: 5,
    ratingCount: 30,
    discount: "-35%",
    brand: "Nokia",
    color: "Blue",
    vendor: "Vendor2",
    categories: ["HeadPhones"],
  },
  {
    id: 3,
    name: "RGB liquid CPU Cooler",
    image: "/images/pro-3.png",
    price: "$160",
    prevPrice: "$170",
    rating: 4,
    ratingCount: 50,
    discount: "-40%",
    brand: "Samsung",
    color: "Yellow",
    vendor: "Vendor3",
    categories: ["Computers"],
  },
  {
    id: 4,
    name: "Small Bookshelf",
    image: "/images/pro-4.png",
    price: "$360",
    prevPrice: "$460",
    rating: 5,
    ratingCount: 100,
    discount: "-40%",
    brand: "Apple",
    color: "Green",
    vendor: "Vendor4",
    categories: ["Home Appliances"],
  },
  {
    id: 5,
    name: "The Eos Camera",
    image: "/images/camera.png",
    price: "$260",
    prevPrice: "$360",
    rating: 4,
    ratingCount: 65,
    brand: "Samsung",
    color: "Yellow",
    vendor: "Vendor1",
    categories: ["Camera"],
  },
  {
    id: 6,
    name: "The Teddy",
    image: "/images/teddy.jpg",
    price: "$260",
    prevPrice: "$360",
    rating: 4,
    ratingCount: 65,
    brand: "Nokia",
    color: "Blue",
    vendor: "Vendor2",
    categories: ["SmartWatch"],
  },
  {
    id: 7,
    name: "The Jacket",
    image: "/images/jacket.png",
    price: "$260",
    prevPrice: "$360",
    rating: 4,
    ratingCount: 65,
    brand: "Apple",
    color: "Green",
    vendor: "Vendor3",
    categories: ["Clothing"],
  },
  {
    id: 8,
    name: "The Car",
    image: "/images/car.png",
    price: "$260",
    prevPrice: "$360",
    rating: 4,
    ratingCount: 65,
    brand: "Samsung",
    color: "Yellow",
    vendor: "Vendor4",
    categories: ["Electronics"],
  },
  {
    id: 9,
    name: "The Gamepad",
    image: "/images/gamepad.png",
    price: "$260",
    prevPrice: "$360",
    rating: 4,
    ratingCount: 65,
    brand: "Nokia",
    color: "Blue",
    vendor: "Vendor1",
    categories: ["Gaming"],
  },
  {
    id: 10,
    name: "The Laptop",
    image: "/images/laptop.png",
    price: "$260",
    prevPrice: "$360",
    rating: 4,
    ratingCount: 65,
    brand: "Apple",
    color: "Green",
    vendor: "Vendor2",
    categories: ["Computers"],
  },
  {
    id: 11,
    name: "The Shoe",
    image: "/images/shoe.png",
    price: "$260",
    prevPrice: "$360",
    rating: 4,
    ratingCount: 65,
    brand: "Samsung",
    color: "Yellow",
    vendor: "Vendor3",
    categories: ["Clothing"],
  },
  {
    id: 12,
    name: "The Watch",
    image: "/images/shoe.png",
    price: "$260",
    prevPrice: "$360",
    rating: 4,
    ratingCount: 65,
    brand: "Apple",
    color: "Green",
    vendor: "Vendor4",
    categories: ["Electronics"],
  },
  {
    id: 13,
    name: "The Watch",
    image: "/images/shoe.png",
    price: "$260",
    prevPrice: "$360",
    rating: 4,
    ratingCount: 65,
    brand: "Samsung",
    color: "Yellow",
    vendor: "Vendor1",
    categories: ["Electronics"],
  },
  {
    id: 14,
    name: "The Watch",
    image: "/images/shoe.png",
    price: "$260",
    prevPrice: "$360",
    rating: 4,
    ratingCount: 65,
    brand: "Nokia",
    color: "Blue",
    vendor: "Vendor2",
    categories: ["Electronics"],
  },
  {
    id: 15,
    name: "The Watch",
    image: "/images/shoe.png",
    price: "$260",
    prevPrice: "$360",
    rating: 4,
    ratingCount: 65,
    brand: "Apple",
    color: "Green",
    vendor: "Vendor3",
    categories: ["Accessories"],
  },
  {
    id: 16,
    name: "The Watch",
    image: "/images/shoe.png",
    price: "$260",
    prevPrice: "$360",
    rating: 4,
    ratingCount: 65,
    brand: "Samsung",
    color: "Yellow",
    vendor: "Vendor4",
    categories: ["Accessories"],
  },
  {
    id: 17,
    name: "The Watch",
    image: "/images/shoe.png",
    price: "$260",
    prevPrice: "$360",
    rating: 4,
    ratingCount: 65,
    brand: "Nokia",
    color: "Blue",
    vendor: "Vendor1",
    categories: ["Accessories"],
  },
  {
    id: 18,
    name: "The Watch",
    image: "/images/shoe.png",
    price: "$260",
    prevPrice: "$360",
    rating: 4,
    ratingCount: 65,
    brand: "Nokia",
    color: "Blue",
    vendor: "Vendor1",
    categories: ["Phones", "Camera"],
  },
  {
    id: 19,
    name: "The Watch",
    image: "/images/shoe.png",
    price: "$260",
    prevPrice: "$360",
    rating: 4,
    ratingCount: 65,
    brand: "Nokia",
    color: "Blue",
    vendor: "Vendor1",
    categories: ["Phones"],
  },
  {
    id: 20,
    name: "The Watch",
    image: "/images/shoe.png",
    price: "$260",
    prevPrice: "$360",
    rating: 4,
    ratingCount: 65,
    brand: "Nokia",
    color: "Blue",
    vendor: "Vendor1",
    categories: ["Phones"],
  },
  {
    id: 21,
    name: "The Watch",
    image: "/images/shoe.png",
    price: "$260",
    prevPrice: "$360",
    rating: 4,
    ratingCount: 65,
    brand: "Nokia",
    color: "Blue",
    vendor: "Vendor1",
    categories: ["Camera"],
  },
  {
    id: 22,
    name: "The Watch",
    image: "/images/shoe.png",
    price: "$260",
    prevPrice: "$360",
    rating: 4,
    ratingCount: 65,
    brand: "Samsung",
    color: "Red",
    vendor: "Vendor2",
    categories: ["Phones", "HeadPhones"],
  },
  {
    id: 23,
    name: "The Necklace",
    image: "/images/jewelery.png",
    price: "$260",
    prevPrice: "$360",
    rating: 4,
    ratingCount: 65,
    brand: "Gold",
    color: "Yellow",
    vendor: "Vendor3",
    categories: ["jewelery"],
  },
  {
    id: 24,
    name: "The Ring",
    image: "/images/jewelery.png",
    price: "$260",
    prevPrice: "$360",
    rating: 4,
    ratingCount: 65,
    brand: "Diamond",
    color: "White",
    vendor: "Vendor4",
    categories: ["jewelery"],
  },
]);
  
  const categoryName = computed(() => {
  const category = categories.value.find(cat => cat.id === parseInt(categoryId.value));
  return category ? category.name : 'Category';
});

const filteredProducts = computed(() => {
  const category = categories.value.find(cat => cat.id === parseInt(categoryId.value));
  if (category) {
    return products.value.filter(product => product.categories.includes(category.name));
  }
  return [];
});
  </script>
  
  <style>
  /* Add any custom styles here */
  </style>
  